# Generated by Django 4.0.1 on 2026-01-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemenBereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordnung', models.PositiveSmallIntegerField(unique=True)),
                ('thema', models.CharField(max_length=30)),
                ('farbe', models.CharField(choices=[('rot', 'Rot'), ('orange', 'Orange'), ('gelb', 'Gelb'), ('gruen', 'Grün'), ('blau', 'Blau'), ('violett', 'Violett'), ('grau', 'Grau')], max_length=25)),
            ],
            options={
                'verbose_name': 'Themenbereich',
                'verbose_name_plural': 'Themenbereiche',
                'ordering': ['ordnung'],
            },
        ),
        migrations.CreateModel(
            name='Kapitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeile', models.PositiveSmallIntegerField()),
                ('kapitel', models.CharField(max_length=50)),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapitel', to='physik.themenbereich')),
            ],
            options={
                'verbose_name': 'Kapitel',
                'verbose_name_plural': 'Kapitel',
                'ordering': ['thema__ordnung', 'zeile'],
            },
        ),
        migrations.AddConstraint(
            model_name='kapitel',
            constraint=models.UniqueConstraint(fields=('thema', 'zeile'), name='uniq_kapitel_pro_thema_zeile'),
        ),
    ]
