# Generated by Django 5.0.7 on 2026-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themenbereich',
            name='eingeblendet',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='themenbereich',
            name='farbe',
            field=models.CharField(max_length=40),
        ),
    ]
