# Generated by Django 5.0.7 on 2026-01-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0002_themenbereich_eingeblendet_alter_themenbereich_farbe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AufgabenTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='z.B. a3, u23o34, l52, w', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Kurzname, z.B. 'Auswahl mit 3 Optionen'", max_length=100)),
                ('beschreibung', models.TextField(help_text='Ausführliche Erklärung des Typs')),
                ('beispiel', models.TextField(blank=True, help_text='Beispiel-Aufgabe oder Erklärung')),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schwierigkeit', models.SmallIntegerField(default=0)),
                ('frage', models.CharField(blank=True, max_length=50)),
                ('einheit', models.CharField(blank=True, max_length=15)),
                ('anmerkung', models.CharField(blank=True, max_length=50)),
                ('erklärung', models.CharField(blank=True, max_length=50)),
                ('hilfe', models.CharField(blank=True, max_length=50)),
                ('antwort', models.CharField(blank=True, max_length=100)),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='erstellt')),
                ('kapitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='physik.kapitel')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='physik.themenbereich')),
                ('von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_aufgaben', to=settings.AUTH_USER_MODEL)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aufgaben', to='physik.aufgabentyp')),
            ],
        ),
    ]
