# Generated by Django 5.0.7 on 2026-01-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0003_aufgabentyp_aufgabe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabentyp',
            options={'verbose_name': 'Aufgabentyp', 'verbose_name_plural': 'Aufgabentypen'},
        ),
    ]
