# Generated by Django 5.0.7 on 2026-01-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0004_alter_aufgabentyp_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='erklärung',
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='erklaerung',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='antwort',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='erstellt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='frage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='hilfe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AufgabeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionen', to='physik.aufgabe')),
            ],
        ),
    ]
