# Generated by Django 5.0.7 on 2026-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0005_remove_aufgabe_erklärung_aufgabe_erklaerung_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabe',
            options={'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='anmerkung',
            field=models.CharField(blank=True, max_length=255, verbose_name='Anmerkung'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='erklaerung',
            field=models.CharField(blank=True, max_length=255, verbose_name='Erklärung'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='hilfe',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hilfe'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='schwierigkeit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Einfach'), (2, 'Mittel'), (3, 'Profi')], default=1),
        ),
    ]
