# Generated by Django 5.0.7 on 2026-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0006_alter_aufgabe_options_alter_aufgabe_anmerkung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='typ',
            field=models.CharField(blank=True, max_length=20, verbose_name='Typ'),
        ),
        migrations.DeleteModel(
            name='AufgabenTyp',
        ),
    ]
