# Generated by Django 5.0.7 on 2026-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0007_alter_aufgabe_typ_delete_aufgabentyp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabeoption',
            options={'ordering': ['position'], 'verbose_name': 'Option', 'verbose_name_plural': 'Optionen'},
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='anmerkung',
            field=models.CharField(blank=True, help_text='Optional, nur wenn gewünscht.', max_length=255, verbose_name='Anmerkung'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='antwort',
            field=models.CharField(blank=True, help_text='Hier steht die offizielle Antwort.', max_length=255, verbose_name='Antwort'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='einheit',
            field=models.CharField(blank=True, help_text='Optional – wird hinter dem Eingabefeld angezeigt (z.B. cm, kg, °C).', max_length=15, verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='erklaerung',
            field=models.CharField(blank=True, help_text='Optional. Wird angezeigt, wenn auf »Lösung« geklickt wird oder eine falsche Eingabe gemacht wurde.', max_length=255, verbose_name='Erklärung'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='erstellt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='frage',
            field=models.CharField(blank=True, max_length=255, verbose_name='Frage'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='hilfe',
            field=models.CharField(blank=True, help_text='Optional, nur wenn gewünscht.', max_length=255, verbose_name='Hilfe'),
        ),
        migrations.AlterField(
            model_name='aufgabeoption',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='aufgabeoption',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterUniqueTogether(
            name='aufgabeoption',
            unique_together={('aufgabe', 'position')},
        ),
    ]
