# Generated by Django 5.0.7 on 2026-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0008_alter_aufgabeoption_options_alter_aufgabe_anmerkung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabeoption',
            name='lfd_nr',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='lfd_Nr'),
            preserve_default=False,
        ),
    ]
