# Generated by Django 4.0.1 on 2026-01-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0009_aufgabeoption_lfd_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabeoption',
            name='lfd_nr',
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='lfd_nr',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='lfd_Nr'),
            preserve_default=False,
        ),
    ]
