# Generated by Django 4.0.1 on 2026-01-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0010_remove_aufgabeoption_lfd_nr_aufgabe_lfd_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='erklaerung',
            field=models.TextField(blank=True, help_text='Optional. Wird angezeigt, wenn auf »Lösung« geklickt wird oder eine falsche Eingabe gemacht wurde.', verbose_name='Erklärung'),
        ),
    ]
