# Generated by Django 5.0.7 on 2026-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0011_alter_aufgabe_erklaerung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapitel',
            name='kapitel',
            field=models.CharField(max_length=100),
        ),
    ]
