# Generated by Django 4.0.1 on 2026-01-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0012_alter_kapitel_kapitel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AufgabeBild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('bild', models.ImageField(upload_to='aufgabenbilder/')),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='physik.aufgabe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
