# Generated by Django 4.0.1 on 2026-01-11 21:10

from django.db import migrations, models
import physik.models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0013_aufgabebild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabebild',
            name='bild',
            field=models.ImageField(upload_to=physik.models.AufgabeBild.bild_pfad),
        ),
    ]
