# Generated by Django 4.0.1 on 2026-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0014_alter_aufgabebild_bild'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='kurz',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
