# Generated by Django 4.0.1 on 2026-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0015_aufgabe_kurz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='kurz',
        ),
        migrations.AddField(
            model_name='themenbereich',
            name='kurz',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
