# Generated by Django 4.0.1 on 2026-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0016_remove_aufgabe_kurz_themenbereich_kurz'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='fuzzy_toleranz',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = streng, 1 = kleine Fehler erlaubt, 2 = großzügiger'),
        ),
    ]
