# Generated by Django 5.0.7 on 2026-01-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0017_aufgabe_fuzzy_toleranz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='fuzzy_toleranz',
        ),
    ]
