# Generated by Django 4.0.1 on 2026-01-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0018_remove_aufgabe_fuzzy_toleranz'),
    ]

    operations = [
        migrations.CreateModel(
            name='FehlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingegebene_antwort', models.TextField()),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fehler_logs', to='physik.aufgabe')),
            ],
            options={
                'ordering': ['-zeitpunkt'],
            },
        ),
    ]
