# Generated by Django 4.0.1 on 2026-01-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physik', '0019_fehlerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.IntegerField(default=2)),
                ('letzte_bearbeitung', models.DateTimeField(auto_now=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physik.aufgabe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lernkärtchen-Protokoll',
                'verbose_name_plural': 'Lernkärtchen-Protokolle',
                'unique_together': {('user', 'aufgabe')},
            },
        ),
    ]
