# Generated by Django 5.0.7 on 2026-01-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0020_protokoll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aufgabe',
            old_name='antwort',
            new_name='loesung',
        ),
    ]
