# Generated by Django 5.0.7 on 2026-01-31 12:54

import physik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0021_rename_antwort_aufgabe_loesung'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabebild',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=physik.models.bild_pfad),
        ),
    ]
