# Generated by Django 5.0.7 on 2026-01-31 15:32

import physik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0022_aufgabebild_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabebild',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=physik.models.bild_pfad),
        ),
    ]
