# Generated by Django 4.0.1 on 2026-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0023_alter_aufgabebild_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabeoption',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position'),
        ),
    ]
