# Generated by Django 4.0.1 on 2026-02-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0024_alter_aufgabeoption_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabebild',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
