# Generated by Django 5.0.7 on 2026-02-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0022_profil'),
        ('physik', '0025_alter_aufgabebild_position'),
    ]

    operations = [
    ]
