# Generated by Django 5.0.7 on 2026-02-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0026_merge_0022_profil_0025_alter_aufgabebild_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='zeichen',
            field=models.CharField(blank=True, help_text='Optional – wird vor dem Eingabefeld angezeigt (z.B. F=, R=, l=...).', max_length=10, verbose_name='Formelzeichen'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='einheit',
            field=models.CharField(blank=True, help_text='Optional – wird hinter dem Eingabefeld angezeigt (z.B. cm, kg, °C).', max_length=10, verbose_name='Einheit'),
        ),
    ]
