# Generated by Django 5.0.7 on 2026-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0027_aufgabe_zeichen_alter_aufgabe_einheit'),
    ]

    operations = [
        migrations.AddField(
            model_name='themenbereich',
            name='kapitel_unabhaengig',
            field=models.BooleanField(default=False),
        ),
    ]
