# Generated by Django 5.0.7 on 2026-02-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0028_themenbereich_kapitel_unabhaengig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='typ',
            field=models.CharField(max_length=20, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='themenbereich',
            name='kapitel_unabhaengig',
            field=models.BooleanField(default=False, verbose_name='Kapitel unabhängig'),
        ),
    ]
