# Generated by Django 5.0.7 on 2026-02-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physik', '0029_alter_aufgabe_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='frage',
            field=models.CharField(max_length=255, verbose_name='Frage'),
        ),
    ]
